In [63]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

1.Spliting the Dataset to independenat variables and dependent variables.

In [64]:
df = pd.read_csv("Data.csv")
# The first argument is for rows , and the second is for columns
# values -> return array of values of the columns.
x = df.iloc[: , :-1].values
y = df.iloc[: ,-1].values
y

array(['No', 'Yes', 'No', 'No', 'Yes', 'Yes', 'No', 'Yes', 'No', 'Yes'],
      dtype=object)

2.Manipulate The Missing Values

In [65]:
from sklearn.impute import SimpleImputer
# Replace all the missing values (nan) with the mean vaules of all obeservations.
imputer = SimpleImputer(missing_values =np.nan , strategy = 'mean')
imputer.fit(x[:, 1:])
x[: , 1:] = imputer.transform(x[: , 1:])
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, 63777.77777777778],
       ['France', 35.0, 58000.0],
       ['Spain', 38.77777777777778, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

3. Encoding Catrgorical Data

In [66]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
#  Will proceed the encoder .
# the third arguemnt starts with 0 because the first argument starts with zero. that's means that we need to encode
# the first column.
# [reminder : 'passthrough' means that we want the remaining columns with the same encoding and value.]
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])],remainder='passthrough')
# fit() is implemented by every estimator and it accepts an input for the sample data ( X )
# will return a new metrics of (x) with three columns oneHotEncoding 
# we want to take the output of this method as a numpy array.
x = np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, 44.0, 72000.0],
       [0.0, 0.0, 1.0, 27.0, 48000.0],
       [0.0, 1.0, 0.0, 30.0, 54000.0],
       [0.0, 0.0, 1.0, 38.0, 61000.0],
       [0.0, 1.0, 0.0, 40.0, 63777.77777777778],
       [1.0, 0.0, 0.0, 35.0, 58000.0],
       [0.0, 0.0, 1.0, 38.77777777777778, 52000.0],
       [1.0, 0.0, 0.0, 48.0, 79000.0],
       [0.0, 1.0, 0.0, 50.0, 83000.0],
       [1.0, 0.0, 0.0, 37.0, 67000.0]], dtype=object)

In [67]:
from sklearn.preprocessing import LabelEncoder
# We do not need to put any thing in the parenthess becasue we have a single vector.
le =LabelEncoder()
y = le.fit_transform(y)
y

array([0, 1, 0, 0, 1, 1, 0, 1, 0, 1])

In [68]:
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x , y , test_size = 0.2 , random_state =1)

In [31]:
print(x_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [69]:
print(x_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [70]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [71]:
print(y_test)

[0 1]


4. Feature Scaling

In [74]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[: , 3:] = sc.fit_transform(x_train[: , 3:])
x_test[: , 3:] = sc.transform(x_test[: , 3:])
# x_train[: , 3:]
print(x_test)

[[0.0 1.0 0.0 -1.4661817944830127 -0.9069571034860731]
 [1.0 0.0 0.0 -0.44973664397484425 0.20564033932253029]]
